version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip --version  # Check pip version
      - python --version  # Check Python version
      - echo "Listing available packages:"
      - pip list  # List installed packages (if any)
      - echo "Attempting to install from requirements.txt..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on $(date)
      - python hello_world.py
  post_build:
    commands:
      - echo Build completed on $(date)

artifacts:
  files:
    - hello_world.py

